--Checking for duplicate and null values
SELECT ID,
LINK,
SAMPLING_POINT,
SAMPLINGPOINT_NOTATION,
SAMPLINGPOINT_LABEL,
SAMPLE_DATETIME,
DETERMINAND_LABEL,
DETERMINAND_DEFINITION,
RESULT_QUALIFIERNOTATION,
RESULT,
CODED_RESULTINTERPRETATIONINTERPRETATION,
DETERMINAND_UNITLABEL,
SAMPLE_SAMPLEDMATERIALTYPELABEL,
SAMPLE_ISCOMPLIANCESAMPLE,
SAMPLE_PURPOSELABEL,
SAMPLING_POINTEASTING,
SAMPLING_POINTNORTHING,
DETERMINANDNOTATION,
SAMPLEDATE,
SAMPLETIME, COUNT(*)
FROM WATERQUALITY
GROUP BY
ID,
LINK,
SAMPLING_POINT,
SAMPLINGPOINT_NOTATION,
SAMPLINGPOINT_LABEL,
SAMPLE_DATETIME,
DETERMINAND_LABEL,
DETERMINAND_DEFINITION,
RESULT_QUALIFIERNOTATION,
RESULT,
CODED_RESULTINTERPRETATIONINTERPRETATION,
DETERMINAND_UNITLABEL,
SAMPLE_SAMPLEDMATERIALTYPELABEL,
SAMPLE_ISCOMPLIANCESAMPLE,
SAMPLE_PURPOSELABEL,
SAMPLING_POINTEASTING,
SAMPLING_POINTNORTHING,
DETERMINANDNOTATION,
SAMPLEDATE,
SAMPLETIME
HAVING COUNT(*)>1;

--Changing datatype of determinand notation from binary double to number

ALTER TABLE WATERQUALITY ADD DETER_NOTATION NUMBER;

UPDATE WATERQUALITY SET DETER_NOTATION = CAST(determinand_notation as number);

ALTER TABLE WATERQUALITY RENAME COLUMN DETER_NOTATION TO DETERMINANDNOTATION;

ALTER TABLE WATERQUALITY DROP COLUMN DETERMINAND_NOTATION;

SELECT DETERMINANDNOTATION from WATERQUALITY;

--splitting the time column into data and time

ALTER TABLE WATERQUALITY ADD SAMPLEDATE VARCHAR2(255);

UPDATE WATERQUALITY SET SAMPLEDATE = SUBSTR("SAMPLE_DATETIME",1,10);

ALTER TABLE WATERQUALITY ADD SAMPLETIME VARCHAR2(255);

UPDATE WATERQUALITY SET SAMPLETIME = SUBSTR("SAMPLE_DATETIME",12);

SELECT SAMPLEDATE,SAMPLETIME FROM WATERQUALITY;



