CREATE TABLE DETERMINAND_DIM(	
	DETERMINAND_ID NUMBER, 
	DETERMINAND_LABEL VARCHAR2(255), 
	DETERMINAND_DEF VARCHAR2(255), 
	DETERMINAND_UNIT_LABEL VARCHAR2(255), 
	CONSTRAINT DETERMINAND_ID_PK PRIMARY KEY (DETERMINAND_ID)   
	);

CREATE TABLE SAMPLE_DIM(	
	 SAMPLE_ID VARCHAR2(255), 
	 SAMPLE_SAMPLING_POINT VARCHAR2(255), 
	 SAMPLE_SAMPLING_POINT_NOTATION VARCHAR2(255), 
	 SAMPLE_POINT_LABEL VARCHAR2(255), 
	 SAMPLE_MATERIAL_TYPE_LABEL VARCHAR2(255), 
	 SAMPLE_COMPLIANCE VARCHAR2(5), 
	 SAMPLE_PURPOSE_LABEL VARCHAR2(255), 
	 SAMPLE_POINT_NORTHING VARCHAR2(255), 
	 SAMPLE_POINT_EASTING VARCHAR2(255), 
	 CONSTRAINT SAMPLE_ID_PK PRIMARY KEY (SAMPLE_ID)
    );

CREATE TABLE TIME(	
	SAMPLE_DATE DATE NOT NULL, 
	SAMPLE_TIME TIMESTAMP(6) NOT NULL, 
	TIME_ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1), 
	SAMPLE_WEEK NUMBER, 
	SAMPLE_MONTH NUMBER, 
	SAMPLE_YEAR NUMBER, 
	CONSTRAINT TIME_DIM_PK PRIMARY KEY (TIME_ID)
	);
    
CREATE TABLE FACT_TABLE(
	SAMPLE_ID VARCHAR2(255) NOT NULL, 
	DETERMINAND_ID NUMBER, 
	SAMPLE_MATERIAL_TYPE VARCHAR2(255), 
	RESULT NUMBER(16,8), 
	SAMPLE_PURPOSE VARCHAR2(255), 
	TIME_ID NUMBER, 
	CONSTRAINT DETERMINAND_ID_FK FOREIGN KEY (DETERMINAND_ID)
	REFERENCES DETERMINAND_DIM (DETERMINAND_ID),
	CONSTRAINT SAMPLE_ID_FK FOREIGN KEY (SAMPLE_ID)
	REFERENCES SAMPLE_DIM (SAMPLE_ID), 
	CONSTRAINT TIME_ID_FK FOREIGN KEY (TIME_ID)
	REFERENCES TIME_DIM (TIME_ID)
	);