---populating fact table and dimension table
--sample dimension
declare
Cursor s_sample is
select "LINK","SAMPLING_POINT","SAMPLINGPOINT_NOTATION","SAMPLINGPOINT_LABEL","SAMPLE_SAMPLEDMATERIALTYPELABEL","SAMPLE_ISCOMPLIANCESAMPLE",
"SAMPLE_PURPOSELABEL","SAMPLING_POINTEASTING","SAMPLING_POINTNORTHING" from waterquality;
begin
for s_sam in s_sample loop
insert into SAMPLE_DIM(SAMPLE_ID,SAMPLE_SAMPLING_POINT,SAMPLE_SAMPLING_POINT_NOTATION,SAMPLE_POINT_LABEL,SAMPLE_MATERIAL_TYPE_LABEL,SAMPLE_COMPLIANCE
,SAMPLE_PURPOSE_LABEL,SAMPLE_POINT_EASTING,SAMPLE_POINT_NORTHING)
values(s_sam."LINK",s_sam."SAMPLING_POINT",s_sam."SAMPLINGPOINT_NOTATION",s_sam."SAMPLINGPOINT_LABEL",s_sam."SAMPLE_SAMPLEDMATERIALTYPELABEL",s_sam."SAMPLE_ISCOMPLIANCESAMPLE",
s_sam."SAMPLE_PURPOSELABEL",s_sam."SAMPLING_POINTEASTING",s_sam."SAMPLING_POINTNORTHING" );
end loop;
end;

--determinand dim
declare
Cursor s_sample is
select distinct "DETERMINANDNOTATION","DETERMINAND_LABEL","DETERMINAND_DEFINITION","DETERMINAND_UNITLABEL" from waterquality;
begin
for s_sam in s_sample loop
insert into DETERMINAND_DIM(DETERMINAND_ID,DETERMINAND_LABEL,DETERMINAND_DEF,DETERMINAND_UNIT_LABEL)
values(s_sam."DETERMINANDNOTATION",s_sam."DETERMINAND_LABEL",s_sam."DETERMINAND_DEFINITION",s_sam."DETERMINAND_UNITLABEL");
end loop;
end;

--time dim
declare
Cursor s_sample is
select "SAMPLEDATE","SAMPLETIME","SAMPLEWEEK","SAMPLEMONTH","SAMPLEYEAR" from waterquality;
begin
for s_sam in s_sample loop
insert into TIME_DIM(SAMPLE_DATE,SAMPLE_TIME,SAMPLE_WEEK,SAMPLE_MONTH,SAMPLE_YEAR)
values(s_sam."SAMPLEDATE",s_sam."SAMPLETIME",s_sam."SAMPLEWEEK",s_sam."SAMPLEMONTH",s_sam."SAMPLEYEAR");
end loop;
end;

--fact table
declare
CURSOR F_sample is
SELECT "LINK", ID, SAMPLE_ID,TIME_ID, DETERMINANDNOTATION,DETERMINAND_ID, "SAMPLE_SAMPLEDMATERIALTYPELABEL",RESULT,"SAMPLE_PURPOSELABEL"
from waterquality W, SAMPLE_DIM S,TIME_DIM T,DETERMINAND_DIM D
WHERE W."LINK" = S.SAMPLE_ID AND W."ID" = T.TIME_ID AND W.DETERMINANDNOTATION = D.DETERMINAND_ID;
begin
for F_sam in F_sample loop
insert into FACT_TABLE(SAMPLE_ID,DETERMINAND_ID,SAMPLE_MATERIAL_TYPE,RESULT,SAMPLE_PURPOSE,TIME_ID)
VALUES (F_sam."LINK",F_sam.DETERMINAND_NOTATION,F_sam."SAMPLE_SAMPLEDMATERIALTYPELABEL",F_sam.RESULT,F_sam."SAMPLE_PURPOSELABEL",F_sam.TIME_ID);
end loop;
end;


